apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: transactions
  name: transactions
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30080
  selector:
    app: transactions
