apiVersion: v1
kind: Pod
metadata:
  labels:
    run: adminer
  name: adminer
spec:
  containers:
  - image: adminer
    name: adminer
    env:
    - name: ADMINER_DEFAULT_SERVER
      value: postgres-svc