apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: adminer
  name: adminer
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30090
  selector:
    run: adminer
  type: NodePort
status:
  loadBalancer: {}