apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: transaction-nightly
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/mmkmou/lfc-tp-services-kust'
    path: overlays/dev
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true